### ISSUE TITLE
Implement Sentiment Analysis on Repos Comments/Messages

### ISSUE THREAD

**Issue by syedtihaamahmad** [Simon-SS/augur_view_group_12#6]
Analyze the positive and negative sentiments from issues comments/messages to derive the success and health of a project which is the main goal of AUGUR.
## Tasks
- [x] Setup Augur
 https://oss-augur.readthedocs.io/en/main/development-guide/installation.html
- [x] Create new workers to pull data
As mentioned in the documentation, I can create a new worker or modify already available workers to extract data such as Gitlab Issues Worker - Populated Models to fill a database with (issue_messages,  issues etc.)
https://oss-augur.readthedocs.io/en/main/development-guide/workers/creating_a_new_worker.html
- [x] A schema available in the docs as "Messages" could be used to get data for our ML task
![image](https://user-images.githubusercontent.com/25120634/202591473-88346542-d973-492b-a930-9be7cabf7a34.png)
- [x] Clean data/ Data preprocessing
- [x] Implement a ML/DL base sentiment analysis algorithm
A popular and very recent SOTA Hugging Face can be deployed to perform accurate sentiment analysis https://blog.doit-intl.com/performing-surprisingly-easy-sentiment-analysis-on-google-cloud-platform-fc26b2e2b4b
- [x] Provide with sentiment scores
- [x] Try to visualize the scores on Augurview

**Comment by syedtihaamahmad** [comment]
All tasks done!
